name: Build .NET Framework 4.7.2

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore H5PtoPPTX.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build solution
        run: msbuild H5PtoPPTX.sln /p:Configuration=Release

      # Uncomment and adjust the following if you have tests
      # - name: Run tests
      #   run: |
      #     vstest.console.exe "path\to\YourTestProject.dll"
